import { useEffect, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Bot, Send, Sparkles, ShieldCheck, Brain } from 'lucide-react';
import PanelCard from '../PanelCard';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import { bus, EVENTS } from '../../lib/eventBus';
import { copilotChat } from '../../lib/api';
import { useRealtime } from '../../lib/useRealtime';
import { selectExplanation } from '../../lib/selectors';
























const SEED = [
{
  id: 1,
  role: 'ai',
  text:
  'SentinelAI online. Streaming live pipeline events from the backend — ' +
  'I will summarize each detection as it arrives and propose actions.',
  reasoning:
  'WebSocket /ws/live attached. Awaiting first PipelineResult.',
  ts: '—'
}];


const SUGGESTIONS = [
'Summarize the last 5 critical alerts',
'What action would you take on the latest threat?',
'Draft an incident report'];




const TYPING_MS = 900;


const MAX_MESSAGES = 50;


const MAX_QUEUE = 5;

const fmtTime = (iso) => {
  const d = iso ? new Date(iso) : new Date();
  return d.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
};

let nextId = 1000;


function buildAiMessage(explanation) {
  const reasoningParts = [];
  if (explanation?.why_flagged) reasoningParts.push(explanation.why_flagged);
  if (explanation?.actions_taken) reasoningParts.push(explanation.actions_taken);
  return {
    id: ++nextId,
    role: 'ai',
    text: explanation?.summary ?? 'Detection completed.',
    reasoning: reasoningParts.join('  '),
    ts: fmtTime(explanation?.generated_at)
  };
}

function buildSystemBanner(label) {
  return {
    id: ++nextId,
    role: 'system',
    text: `Sim launched: ${label}`,
    ts: fmtTime()
  };
}

export default function AICopilotPanel() {
  const explanation = useRealtime(selectExplanation);

  const [messages, setMessages] = useState(SEED);
  const [queue, setQueue] = useState([]);
  const [thinking, setThinking] = useState(false);
  const [input, setInput] = useState('');



  const lastSeenRef = useRef(null);
  const scrollRef = useRef(null);


  useEffect(() => {
    scrollRef.current?.scrollTo({
      top: scrollRef.current.scrollHeight,
      behavior: 'smooth'
    });
  }, [messages, thinking]);


  useEffect(() => {
    if (!explanation) return;


    if (lastSeenRef.current === explanation) return;
    lastSeenRef.current = explanation;
    setQueue((q) => [...q, explanation].slice(-MAX_QUEUE));
  }, [explanation]);


  useEffect(() => {
    if (thinking) return;
    if (queue.length === 0) return;

    const start = setTimeout(() => setThinking(true), 0);
    const timer = setTimeout(() => {
      const next = queue[0];
      setMessages((m) => [...m, buildAiMessage(next)].slice(-MAX_MESSAGES));
      setQueue((q) => q.slice(1));
      setThinking(false);
    }, TYPING_MS);
    return () => {
      clearTimeout(start);
      clearTimeout(timer);
    };
  }, [thinking, queue]);


  useEffect(() => {
    return bus.on(EVENTS.SIMULATE_REQUEST, (sim) => {
      setMessages((m) => [...m, buildSystemBanner(sim.short)].slice(-MAX_MESSAGES));
    });
  }, []);

  const send = async (text) => {
    const value = (text ?? input).trim();
    if (!value) return;
    setMessages((m) =>
    [...m, { id: ++nextId, role: 'user', text: value, ts: fmtTime() }].
    slice(-MAX_MESSAGES)
    );
    setInput('');


    setThinking(true);
    try {
      const resp = await copilotChat(value);
      setMessages((m) =>
      [
      ...m,
      {
        id: ++nextId,
        role: 'ai',
        text: resp.answer ?? 'No response returned.',
        reasoning: 'Generated by backend copilot provider.',
        ts: fmtTime()
      }].
      slice(-MAX_MESSAGES)
      );
    } catch (err) {
      setMessages((m) =>
      [
      ...m,
      {
        id: ++nextId,
        role: 'ai',
        text: `Copilot unavailable: ${err?.message ?? 'request failed'}`,
        reasoning: '',
        ts: fmtTime()
      }].
      slice(-MAX_MESSAGES)
      );
    } finally {
      setThinking(false);
    }
  };

  return (
    <PanelCard
      title="AI Copilot"
      subtitle="Live explanations & reasoning"
      accent="cyan"
      tone="primary"
      icon={<Bot className="h-4 w-4" />}
      bodyClassName="p-0"
      actions={
      <Badge variant="cyan" glow>
          <Sparkles className="h-3 w-3" />
          <span className="font-semibold">Sentinel-7</span>
        </Badge>
      }>
      
      <div className="flex flex-col h-full">
        {}
        <div
          ref={scrollRef}
          className="flex-1 overflow-y-auto scrollbar-cyber px-5 py-4 space-y-3"
          style={{ scrollBehavior: 'smooth' }}>
          
          <AnimatePresence initial={false}>
            {messages.map((m) =>
            m.role === 'system' ?
            <SystemBanner key={m.id} message={m} /> :
            <Bubble key={m.id} message={m} />
            )}
            {thinking && <ThinkingBubble />}
          </AnimatePresence>
        </div>

        {}
        <div className="px-5 pb-2 flex flex-wrap gap-1.5">
          {SUGGESTIONS.map((s) =>
          <Button
            key={s}
            variant="outline"
            size="sm"
            onClick={() => send(s)}
            className="h-6 px-2.5 rounded-full text-[11px] font-normal hover:text-neon-cyan hover:border-neon-cyan/40">
            
              {s}
            </Button>
          )}
        </div>

        {}
        <form
          onSubmit={(e) => {
            e.preventDefault();
            send();
          }}
          className="px-4 pb-4 pt-2">
          
          <div className="flex items-center gap-2 h-11 rounded-xl border border-border-subtle bg-bg-sunken/70
                          focus-within:border-neon-cyan/50 focus-within:ring-1 focus-within:ring-neon-cyan/30
                          focus-within:shadow-[0_0_22px_-6px_rgba(0,212,255,0.6)]
                          transition-cyber px-3">


            
            <ShieldCheck className="h-4 w-4 text-neon-cyan shrink-0" />
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask Sentinel…   e.g. ‘isolate compromised hosts’"
              className="flex-1 bg-transparent outline-none text-[13px] text-fg-primary placeholder:text-fg-muted" />
            
            <Button
              type="submit"
              variant="default"
              size="icon"
              disabled={!input.trim()}
              className="h-7 w-7"
              aria-label="Send">
              
              <Send className="h-3.5 w-3.5" />
            </Button>
          </div>
        </form>
      </div>
    </PanelCard>);

}


function SystemBanner({ message }) {
  return (
    <motion.div
      layout
      initial={{ opacity: 0, scale: 0.96 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.32 }}
      className="flex items-center gap-2 my-1"
      role="status">
      
      <span className="flex-1 h-px bg-gradient-to-r from-transparent via-border-strong to-transparent" />
      <span className="px-2 py-0.5 rounded-full font-mono text-[9.5px] uppercase tracking-[0.22em] text-fg-muted border border-border-subtle bg-bg-sunken/70">
        {message.text} · {message.ts}
      </span>
      <span className="flex-1 h-px bg-gradient-to-r from-transparent via-border-strong to-transparent" />
    </motion.div>);

}


function Bubble({ message }) {
  const isAI = message.role === 'ai';
  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 8, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      transition={{ duration: 0.36, ease: [0.2, 0.7, 0.2, 1] }}
      className={`flex gap-2.5 ${isAI ? '' : 'flex-row-reverse'}`}>
      
      <div
        className={[
        'shrink-0 mt-0.5 h-7 w-7 rounded-lg flex items-center justify-center border',
        isAI ?
        'bg-bg-sunken/80 border-neon-cyan/30 text-neon-cyan shadow-[0_0_12px_-4px_rgba(0,212,255,0.7)]' :
        'bg-bg-sunken/80 border-neon-violet/25 text-neon-violet'].
        join(' ')}>
        
        {isAI ? <Bot className="h-3.5 w-3.5" /> : <span className="text-[10px] font-mono">YOU</span>}
      </div>
      <div className={`max-w-[82%] ${isAI ? '' : 'text-right'}`}>
        <div
          className={[
          'inline-block rounded-xl px-3 py-2 text-[13px] leading-snug border transition-cyber text-left',

          isAI ?
          'bg-bg-elevated/85 border-neon-cyan/20 text-fg-primary ' +
          'shadow-[0_0_18px_-8px_rgba(0,212,255,0.45),0_1px_0_0_rgba(255,255,255,0.04)_inset]' :
          'bg-neon-violet/8 border-neon-violet/25 text-fg-primary'].
          join(' ')}>
          
          {message.text}
          {isAI && message.reasoning &&
          <div className="mt-1.5 pt-1.5 border-t border-neon-cyan/15 flex items-start gap-1.5 text-[11px] text-fg-secondary/90 font-mono leading-snug">
              <Brain className="h-3 w-3 mt-[2px] text-neon-cyan/80 shrink-0" />
              <span>{message.reasoning}</span>
            </div>
          }
        </div>
        <div className="mt-1 font-mono text-[10px] uppercase tracking-[0.18em] text-fg-faint">
          {isAI ? 'Sentinel' : 'You'} · {message.ts}
        </div>
      </div>
    </motion.div>);

}


function ThinkingBubble() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -4 }}
      transition={{ duration: 0.24 }}
      className="flex gap-2.5"
      aria-label="Sentinel is composing a response">
      
      <div className="shrink-0 mt-0.5 h-7 w-7 rounded-lg flex items-center justify-center border bg-bg-sunken/80 border-neon-cyan/30 text-neon-cyan shadow-[0_0_12px_-4px_rgba(0,212,255,0.7)]">
        <Bot className="h-3.5 w-3.5" />
      </div>
      <div className="relative inline-flex items-center gap-1 rounded-xl px-3 py-2.5 bg-bg-elevated/85 border border-neon-cyan/20 overflow-hidden shadow-[0_0_18px_-8px_rgba(0,212,255,0.45)]">
        <span
          aria-hidden
          className="absolute inset-0 pointer-events-none"
          style={{
            background:
            'linear-gradient(90deg, transparent 0%, rgba(0,212,255,0.15) 50%, transparent 100%)',
            backgroundSize: '200% 100%',
            animation: 'shimmer 1.6s linear infinite',
            mixBlendMode: 'overlay'
          }} />
        
        <Dot delay={0} />
        <Dot delay={0.15} />
        <Dot delay={0.3} />
      </div>
    </motion.div>);

}

function Dot({ delay }) {
  return (
    <motion.span
      animate={{ opacity: [0.25, 1, 0.25], y: [0, -2, 0] }}
      transition={{ duration: 1, repeat: Infinity, delay }}
      className="relative h-1.5 w-1.5 rounded-full bg-neon-cyan shadow-[0_0_6px_rgba(0,212,255,0.9)]" />);


}